/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Enterprise.Enterprise;
import Business.Organization.CarPoolOrganization;
import Business.Organization.DriverOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CustomerWorkRequest;
import Business.WorkQueue.DriverWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class RequestCarJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form RequestCarJPanel
     */
    public RequestCarJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueLabel.setText(enterprise.getName());
        
        ComboBoxCarType.removeAllItems();
        ComboBoxCarType.addItem("Hatchback");
        ComboBoxCarType.addItem("Sedan");
        ComboBoxCarType.addItem("SUV");
        
        //Ride Type
        ComboBoxCarType1.removeAllItems();
        ComboBoxCarType1.addItem("Pickup & Drop"); //0.2$ per KM
        ComboBoxCarType1.addItem("Rental"); //40$ per day
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        destinationTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sourceTextField = new javax.swing.JTextField();
        ComboBoxCarType = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        ComboBoxCarType1 = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setText("Request Cab");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        jLabel1.setText("Estimate Price Rate:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 130, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        jLabel2.setText("Source");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));
        add(destinationTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 89, -1));

        jLabel3.setText("Destination");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));
        add(sourceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 90, -1));

        ComboBoxCarType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxCarType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCarTypeActionPerformed(evt);
            }
        });
        add(ComboBoxCarType, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 90, -1));

        jLabel4.setText("Car Type");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel5.setText("Ride Type");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        lblPrice.setText("@Price");
        add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 90, -1));

        ComboBoxCarType1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxCarType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCarType1ActionPerformed(evt);
            }
        });
        add(ComboBoxCarType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        
        //String message = messageJTextField.getText();
        String s = sourceTextField.getText();
        String d = destinationTxtField.getText();
        CustomerWorkRequest request = new CustomerWorkRequest();
       // request.setMessage(message);
        request.setSource(s);
        request.setDestination(d);
        request.setCartype(ComboBoxCarType.getSelectedItem().toString());
        request.setRidetype(ComboBoxCarType1.getSelectedItem().toString());
        request.setEstimateprice(lblPrice.getText());
        request.setSender(userAccount);
        request.setStatus("Sent");
        
      
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof CarPoolOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerWorkAreaJPanel dwjp = (CustomerWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void ComboBoxCarTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCarTypeActionPerformed
        if(ComboBoxCarType.getSelectedIndex() == -1){
            return;
        }
        if(ComboBoxCarType.getSelectedItem() == "Hatchback"){
        
        }
        else if(ComboBoxCarType.getSelectedItem() == "Sedan"){
        
        }
        else if(ComboBoxCarType.getSelectedItem() == "SUV"){
        
        }
    }//GEN-LAST:event_ComboBoxCarTypeActionPerformed

    private void ComboBoxCarType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCarType1ActionPerformed
        if(ComboBoxCarType1.getSelectedItem() == "Pickup & Drop"){ //0.2$ per KM
            lblPrice.setText("0.2$ per km");
        }
        else if(ComboBoxCarType1.getSelectedItem() == "Rental"){ //40$ per day
            lblPrice.setText("40$ per day");
        }
    }//GEN-LAST:event_ComboBoxCarType1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxCarType;
    private javax.swing.JComboBox ComboBoxCarType1;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField destinationTxtField;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTextField sourceTextField;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
